sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t terrankartiktellus/avalanche_pups_client -f ./client/Dockerfile ./client
  - docker build -t terrankartiktellus/avalanche_pups_server -f ./server/Dockerfile ./server
  - docker build -t terrankartiktellus/avalanche_pups_worker -f ./worker/Dockerfile ./worker
after_success:
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --username --password-stdin
  # Take those images and push them to docker hub
  - docker push -t terrankartiktellus/avalanche_pups_client
  - docker push -t terrankartiktellus/avalanche_pups_server
  - docker push -t terrankartiktellus/avalanche_pups_worker
  