apiVersion: v1
kind: Service
metadata:
  name:  client-networking-service
spec:
  selector:
    object_label:  web
  type:  NodePort
  ports:
  - name:  client-networking-port
    port:  3050
    targetPort:  3000
    nodePort: 31515
